### ISSUE TITLE
tests fail version 0.11.0 debian/sid

### ISSUE THREAD

**Issue by brianmay** [alex/django-filter#283]
```
python2 ./runtests.py
....................................ssss...s..x.ss..x..x.....................................s..........x..................xx...................E..............u.......x........................x................s..................s....sss.........
======================================================================
ERROR: test_filtering_uses_distinct (tests.test_filters.FilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/tests/test_filters.py", line 192, in test_filtering_uses_distinct
    result = qs.distinct.assert_called_once()
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once

----------------------------------------------------------------------
Ran 245 tests in 0.386s

FAILED (errors=1, skipped=13, expected failures=8, unexpected successes=1)
Creating test database for alias 'default'...
Destroying test database for alias 'default'...
```

**Comment by carltongibson** [comment]
Curious. The CI build is passing.


Can you take a look at the Travis config and see where setup differs? 

What's your Python version etc?

**Comment by brianmay** [comment]
I cannot see any reference to assert_called_once in https://docs.python.org/3/library/unittest.mock.html

Rather I see a function called to assert_called_once_with.

Am wondering if assert_called_once was an undocumented mock function that was removed in Python 3.4.3?

Your tests seem to be using 3.4.2

**Comment by carltongibson** [comment]
OK. That gives me something to go. I'll investigate. 

Thanks for the extra details
