### ISSUE TITLE
AppRegistryNotReady

### ISSUE THREAD

**Issue by vieva** [alex/django-filter#310]
DJANGO 1.8.5 python 3.4 
DJANGO-FILTER 0.11.0

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Vincenzo\Desktop\GIOVANNI BORSI\env\lib\site-packages\django\co
re\management\__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "C:\Users\Vincenzo\Desktop\GIOVANNI BORSI\env\lib\site-packages\django\co
re\management\__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Vincenzo\Desktop\GIOVANNI BORSI\env\lib\site-packages\django\co
re\management\__init__.py", line 177, in fetch_command
    commands = get_commands()
  File "C:\Users\Vincenzo\Desktop\GIOVANNI BORSI\env\lib\functools.py", line 448
, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Users\Vincenzo\Desktop\GIOVANNI BORSI\env\lib\site-packages\django\co
re\management\__init__.py", line 72, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "C:\Users\Vincenzo\Desktop\GIOVANNI BORSI\env\lib\site-packages\django\ap
ps\registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "C:\Users\Vincenzo\Desktop\GIOVANNI BORSI\env\lib\site-packages\django\ap
ps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by carltongibson** [comment]
Nothing to suggest this is a Django go filter issue. Make sure you're not using your models at import time.
