### ISSUE TITLE
Pass complex filters in fields array

### ISSUE THREAD

**Issue by sallyruthstruik** [alex/django-filter#333]
Test example:

```{python}
class F(FilterSet):
    class Meta:
        model = User
        fields = ["username__icontains"]

f = F({"username__icontains": "a"}, queryset=self.qs)
self.assertEqual(f.qs.count(), 2)
self.assertQuerysetEqual(f.qs, self.qs.filter(username__icontains="a"))
```

raises exception: 
```
Traceback (most recent call last):
  File "/home/stas/workspace/partners/park.dp.vpn/libs/django-filter/tests/test_filterset.py", line 663, in test_some_complex_filter_methods
    class F(FilterSet):
  File "/home/stas/workspace/partners/park.dp.vpn/libs/django-filter/django_filters/filterset.py", line 176, in __new__
    new_class.filter_for_reverse_field)
  File "/home/stas/workspace/partners/park.dp.vpn/libs/django-filter/django_filters/filterset.py", line 90, in filters_for_model
    field = get_model_field(model, f)
  File "/home/stas/workspace/partners/park.dp.vpn/libs/django-filter/django_filters/filterset.py", line 70, in get_model_field
    opts = rel.rel.to._meta
AttributeError: 'NoneType' object has no attribute 'to'
```

**Comment by carltongibson** [comment]
Take a look here: https://django-filter.readthedocs.org/en/latest/usage.html#the-filter

You need to to define the lookup type, either by declaring the filter explicitly, using the dictionary fields syntax or setting the `extra` keyword args in `__init__`.
